# Medidas de Variabilidad

In [ ]:
import polars as pl
import sys
from pathlib import Path

#Para poder utilizar archivos del proyecto
ROOT = Path.cwd().parent 
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
from src.cleaning.preprocessing import pipeline_preprocesamiento
df = pipeline_preprocesamiento()

## Medidas de Variabilidada para la edad de primera union

In [3]:

pl.Config.set_tbl_cols(-1)

df_real = df.filter(
    (pl.col("edad_primer_union").is_not_null()) & 
    (pl.col("edad_primer_union") < 90) &          
    
    (pl.col("num_hijos").is_not_null()) & 
    (pl.col("num_hijos") < 90)                     
)

var_edad = df_real.group_by("sufrio_violencia_pareja").agg([
    pl.col("edad_primer_union").count().alias("n"),
    (pl.col("edad_primer_union").max() - pl.col("edad_primer_union").min()).alias("rango"),
    pl.col("edad_primer_union").var().alias("varianza"),
    pl.col("edad_primer_union").std().alias("desviacion_estandar"),
    (pl.col("edad_primer_union").quantile(0.75) - pl.col("edad_primer_union").quantile(0.25)).alias("IQR"),
    ((pl.col("edad_primer_union").std() / pl.col("edad_primer_union").mean()) * 100).alias("CV_porcentaje")
]).sort("sufrio_violencia_pareja")

var_edad = var_edad.transpose(include_header=True, header_name="Metrica")
var_edad

shape: (7, 3)
┌─────────────────────────┬────────────┬────────────┐
│ Metrica                 ┆ column_0   ┆ column_1   │
│ ---                     ┆ ---        ┆ ---        │
│ str                     ┆ f64        ┆ f64        │
╞═════════════════════════╪════════════╪════════════╡
│ sufrio_violencia_pareja ┆ 0.0        ┆ 1.0        │
│ n                       ┆ 15210.0    ┆ 8467.0     │
│ rango                   ┆ 76.0       ┆ 72.0       │
│ varianza                ┆ 117.334875 ┆ 110.523091 │
│ desviacion_estandar     ┆ 10.832122  ┆ 10.512996  │
│ IQR                     ┆ 13.0       ┆ 13.0       │
│ CV_porcentaje           ┆ 108.032143 ┆ 104.86245  │
└─────────────────────────┴────────────┴────────────┘

## Medidas de variabilidad para el número de hijos

In [4]:
var_hijos = df_real.group_by("sufrio_violencia_pareja").agg([
    pl.col("num_hijos").count().alias("n"),
    (pl.col("num_hijos").max() - pl.col("num_hijos").min()).alias("rango"),
    pl.col("num_hijos").var().alias("varianza"),
    pl.col("num_hijos").std().alias("desviacion_estandar"),
    (pl.col("num_hijos").quantile(0.75) - pl.col("num_hijos").quantile(0.25)).alias("IQR"),
    ((pl.col("num_hijos").std() / pl.col("num_hijos").mean()) * 100).alias("CV_porcentaje")
]).sort("sufrio_violencia_pareja")

var_hijos = var_hijos.transpose(include_header=True, header_name="Metrica")
var_hijos

shape: (7, 3)
┌─────────────────────────┬───────────┬───────────┐
│ Metrica                 ┆ column_0  ┆ column_1  │
│ ---                     ┆ ---       ┆ ---       │
│ str                     ┆ f64       ┆ f64       │
╞═════════════════════════╪═══════════╪═══════════╡
│ sufrio_violencia_pareja ┆ 0.0       ┆ 1.0       │
│ n                       ┆ 15210.0   ┆ 8467.0    │
│ rango                   ┆ 3.0       ┆ 3.0       │
│ varianza                ┆ 1.371631  ┆ 1.488155  │
│ desviacion_estandar     ┆ 1.171167  ┆ 1.219899  │
│ IQR                     ┆ 2.0       ┆ 3.0       │
│ CV_porcentaje           ┆ 46.154797 ┆ 48.834045 │
└─────────────────────────┴───────────┴───────────┘